### PR TITLE
Harshasi/fail search with low recall

### LINKED ISSUE #102: add recall checks to CI tests
Check the search runs provide non-trivial (say 80+%) recall for the test to pass

### LINKED ISSUE #208: make tests/search_*_index return -1 if no search param has a recall above 70%

### PR DESCRIPTION
**Pull request by harsha-simhadri**
- [ ] Does this PR have a descriptive title that could go in our release notes?
- [ ] Does this PR add any new dependencies?
- [x] Does this PR modify any existing APIs?
   - [x] Is the change to the API backwards compatible?
- [ ] Should this result in any changes to our documentation, either updating existing docs or adding new ones?
 
#### Reference Issues/PRs
Fixes #208 
Fixes #102

#### What does this implement/fix? Briefly explain your changes.
Add an argument to search_disk_index and search_memory_index to return -1 if best recall seen does not exceed threshold. Change CI tests to fail if recall threshold is not met.

### CODE REVIEW

**Review by shanewil — APPROVED** [review]
I don't see any issues with these changes. If test pipeline tests succeed, I'm confident this PR is good.

File: tests/search_memory_index.cpp [hunk 1]
```diff
@@ -295,24 +302,30 @@ int main(int argc, char** argv) {
     return -1;
   }
 
+  if (fail_if_recall_below < 0.0 || fail_if_recall_below >= 100.0) {
```
Comment (shanewil) [inline tests/search_memory_index.cpp:309]: Do you intend this to fail if fail_if_recall_below == 100.0 ?  The message indicates the value should be inclusive of 100%

Comment (harsha-simhadri) [reply tests/search_memory_index.cpp:309]: Yes. 100% recall is not something we should promise with this tool.
